// =========================================================
// AI 툴 가이드 - 서비스 목록 데이터
// 서비스를 추가할 때는 HTML을 건드리지 않고
// 아래 services 배열에 한 덩어리만 더하면 됩니다.
//
// freeLevel : "enough"(무료로 충분) | "taste"(무료는 맛보기) | "paid"(유료 필수)
// korean    : "good"(좋음) | "normal"(보통) | "weak"(약함) | 생략하면 표시 안 함
// purposes  : 아래 PURPOSES의 key (목적으로 찾기에 연결)
// "(조사)" 표시가 붙은 내용은 팀 자료가 아닌 외부 자료 조사 값입니다. (2026.10 기준)
// =========================================================

const CATEGORIES = [
  { key: "video",      label: "동영상 생성·편집", short: "동영상" },
  { key: "automation", label: "자동화",           short: "자동화" },
  { key: "research",   label: "리서치·검색",       short: "리서치" },
  { key: "design",     label: "웹·UI/UX 디자인",   short: "디자인" },
  { key: "image",      label: "이미지 생성·편집",  short: "이미지" },
  { key: "meeting",    label: "회의록·기록",       short: "회의록" },
  { key: "ppt",        label: "시각화·PPT",        short: "PPT" },
  { key: "voice",      label: "음성·번역",         short: "번역·음성" },
  { key: "agent",      label: "범용 AI 에이전트",  short: "에이전트" },
  { key: "coding",     label: "바이브 코딩",       short: "코딩" },
];

const PURPOSES = [
  { key: "meeting",   label: "회의 녹음 정리",       icon: "🎙️" },
  { key: "paper",     label: "논문·근거 찾기",       icon: "📚" },
  { key: "research",  label: "빠른 자료 조사",       icon: "🔎" },
  { key: "slides",    label: "발표자료 만들기",      icon: "📊" },
  { key: "makevideo", label: "영상 만들기",          icon: "🎬" },
  { key: "subtitle",  label: "영상 자막 넣기",       icon: "💬" },
  { key: "promo",     label: "홍보 이미지", icon: "🖼️" },
  { key: "translate", label: "번역·내레이션",        icon: "🌐" },
  { key: "build",     label: "웹·앱 만들기",   icon: "🛠️" },
];

const FREE_LEVELS = {
  enough: { label: "무료로 충분",   emoji: "🟢" },
  taste:  { label: "무료는 맛보기", emoji: "🟡" },
  paid:   { label: "유료 필수",     emoji: "🔴" },
};

const KOREAN_LEVELS = {
  good:   "한국어 좋음",
  normal: "한국어 보통",
  weak:   "한국어 약함",
};

const services = [
  // ---------------- 동영상 생성·편집 ----------------
  {
    name: "Google Flow (Veo)",
    category: "video",
    desc: "Google의 Veo 3.1 모델로 영상을 만드는 제작 도구",
    url: "https://labs.google/flow",
    freeLevel: "taste",
    freeAmount: "하루 50 크레딧 → Lite 모델 약 10~12개 / Fast 모델 약 3~5개 (조사)",
    specSummary: "무료 720p · 최대 8초 · 워터마크 있음",
    useCase: "Google AI Pro 구독 중일 때, 여러 번 고쳐가며 완성도를 높이는 영상 작업",
    purposes: ["makevideo"],
    pros: [
      "Google AI Pro 구독 시 크레딧이 넉넉함",
      "채팅하듯 수정 사항을 바로 반영 가능",
      "영상과 소리를 함께 생성",
    ],
    cons: [
      "생성 전에 크레딧 소모량이 바로 안 보임",
      "기본 설정에 따라 영상 대신 이미지가 나올 수 있음",
      "Veo와 Flow의 이름이 달라 처음에 헷갈림",
    ],
    price: [
      "무료: 하루 50 크레딧 (이월 안 됨)",
      "Google AI Pro: $19.99/월",
      "Google AI Ultra: 상위 요금제 (워터마크 제거는 Ultra만, 조사)",
    ],
    creditTips: [
      "생성 전에 출력 형식이 '영상'인지 먼저 확인하기 (이미지로 나오면 크레딧만 소모됨)",
      "처음에는 가벼운 Lite·Fast 모델로 구도를 잡고, 마음에 들 때 상위 모델로 생성하기",
      "크레딧은 매일 자정 사라지므로 그날 쓸 만큼 나눠서 사용하기",
    ],
    specs: [
      ["무료 해상도", "720p (1080p는 상위 요금제, 조사)"],
      ["최대 길이", "1회 생성 최대 8초 (조사)"],
      ["오디오", "영상과 함께 생성"],
      ["워터마크", "무료·Pro에 'Made with Veo' 표시, Ultra에서 제거 (조사)"],
      ["상업적 이용", "요금제별 이용 조건 확인 필요"],
    ],
  },
  {
    name: "Kling",
    category: "video",
    desc: "사람의 움직임 표현과 가성비가 강점인 영상 생성 서비스",
    url: "https://klingai.com",
    freeLevel: "taste",
    freeAmount: "하루 66 크레딧 → 720p·오디오 끔 5초 영상 약 2개 / 1080p·오디오 포함 약 1개",
    specSummary: "무료 720p 위주 · 5초~ · 워터마크 있음",
    useCase: "비용을 미리 계산하며 짧은 클립을 만드는 작업",
    purposes: ["makevideo"],
    pros: [
      "생성 전에 필요한 크레딧을 바로 확인 가능",
      "해상도, 길이, 오디오 설정이 한눈에 보임",
    ],
    cons: [
      "무료 크레딧으로는 최신 모델 기준 하루 1개 수준 (1080p, 오디오 포함 시 60 크레딧)",
      "인물이 한국인보다 일본인처럼 나왔고 웃는 표정이 다소 어색함 → 프롬프트에 국적 명시 권장",
      "무료 영상에는 워터마크가 붙음",
    ],
    price: [
      "무료: 로그인 크레딧 (확인 시점 66, 하루 단위·이월 안 됨)",
      "Standard: $6.99/월부터 (월 660 크레딧)",
      "상위: Pro, Premier, Ultra",
    ],
    creditTips: [
      "생성 버튼 옆 크레딧 표시를 꼭 확인하고 생성하기",
      "처음엔 720p·오디오 끔으로 테스트하고, 결과가 마음에 들 때 1080p·오디오로 다시 생성하기",
      "인물이 나오면 'A Korean woman in her 30s'처럼 국적을 프롬프트에 적어 재생성 횟수 줄이기",
    ],
    specs: [
      ["무료 해상도", "720p 위주 (1080p는 크레딧이 더 듦)"],
      ["길이", "5초부터 선택 가능"],
      ["오디오", "켜고 끌 수 있음 (켜면 크레딧 증가)"],
      ["워터마크", "무료 영상에는 있음"],
      ["상업적 이용", "무료 플랜은 불가 (조사)"],
    ],
  },
  {
    name: "CapCut",
    category: "video",
    desc: "컷 편집, 자막, 효과, 템플릿을 갖춘 범용 편집기",
    url: "https://www.capcut.com",
    freeLevel: "enough",
    freeAmount: "기본 편집·1080p 내보내기 무료 (무료 소재만 쓰면 워터마크 없음, 조사)",
    specSummary: "무료 1080p · 자동 캡션 횟수 제한",
    useCase: "템플릿과 효과로 꾸미는 숏폼, SNS 홍보 영상",
    purposes: ["subtitle", "makevideo"],
    korean: "good",
    pros: [
      "영상 템플릿이 풍부해 구성과 디자인을 빠르게 잡을 수 있음",
      "자막을 짧게 나눠줘서 화면에 한 번에 뜨는 글자가 적음",
      "AI 이미지·영상 생성도 지원",
      "한국어 음성 인식이 정확했음",
    ],
    cons: [
      "자동 캡션이 월 횟수 제한 (무료 기준)",
      "자막이 문장 중간에서 나뉘어, 문장 단위로 보려면 수동으로 합쳐야 함",
      "Pro 표시가 있는 템플릿·효과를 하나라도 쓰면 워터마크가 붙음 (조사)",
    ],
    price: [
      "무료 플랜 있음",
      "Pro: $19.99/월, 연 $179.99 · 4K 내보내기 (조사)",
    ],
    creditTips: [
      "자동 캡션은 편집을 끝낸 뒤 마지막에 한 번만 돌리기",
      "클립을 하나로 이어 붙인 뒤 자막을 생성하면 횟수를 아낄 수 있음",
      "무료 소재만 쓰면 워터마크 없이 내보낼 수 있으니 Pro 표시 소재는 피하기",
    ],
    specs: [
      ["무료 내보내기", "1080p (조사)"],
      ["워터마크", "무료 소재만 쓰면 없음, Pro 소재 사용 시 붙음 (조사)"],
      ["자동 자막", "무료는 월 횟수 제한"],
      ["유료 내보내기", "4K·HDR (조사)"],
    ],
  },
  {
    name: "Vrew",
    category: "video",
    desc: "음성 인식 자막과 텍스트 기반 컷 편집이 되는 국산 편집기",
    url: "https://vrew.ai/ko",
    freeLevel: "enough",
    freeAmount: "월 200 크레딧 → 자막 작업 약 200분 (짧은 영상도 1분 단위로 차감)",
    specSummary: "해상도 직접 선택 · 내보내기 무제한",
    useCase: "말소리 중심의 설명, 소개, 인터뷰 영상의 자막 작업과 컷 편집",
    purposes: ["subtitle", "makevideo"],
    korean: "good",
    pros: [
      "한 문장을 자막 하나로 묶어줘서 내용 파악이 쉬움",
      "단어 단위로 표시되어 잘못 말한 단어만 골라 지울 수 있음",
      "무음 구간이 표시되어 찾기 쉬움",
      "AI 이미지·영상 생성까지 한 곳에서 가능 (영상 모델 11개 지원)",
    ],
    cons: [
      "짧은 영상도 1분 단위로 크레딧 차감 (8초 영상에 1 크레딧)",
      "문장이 길면 자막 한 줄이 길어져 수동으로 나눠야 함",
    ],
    price: [
      "무료: 월 200 크레딧 (매달 1일 충전, 이월 안 됨, 조사)",
      "유료: 라이트, 스탠다드, 비즈니스",
    ],
    creditTips: [
      "1분 단위로 차감되므로 짧은 클립을 하나로 이어 붙인 뒤 한 번에 자막 생성하기",
      "남은 크레딧은 다음 달로 넘어가지 않으니 월말 전에 쓰기",
    ],
    specs: [
      ["무료 내보내기", "무제한, 해상도 직접 선택 (조사)"],
      ["워터마크", "일부 기능 사용 시 표시, 출처 표기 신청 시 제거 가능 (조사)"],
      ["자동 자막", "월 200 크레딧 안에서, 1분 단위 차감"],
    ],
  },

  // ---------------- 자동화 ----------------
  {
    name: "Make",
    category: "automation",
    desc: "여러 앱을 블록처럼 이어 붙여 반복 업무를 자동화하는 노코드 도구",
    url: "https://www.make.com",
    freeLevel: "enough",
    freeAmount: "월 1,000 크레딧 → 3단계 시나리오 기준 약 330회 실행",
    useCase: "코딩 없이 구글 시트, 메일, 메신저 등 여러 앱 사이의 반복 업무 자동화",
    purposes: [],
    korean: "weak",
    pros: [
      "블록을 이어 붙이는 방식이라 흐름이 한눈에 보임",
      "AI 도우미 Maia에게 말로 설명하면 시나리오 초안을 만들어줌 (베타)",
      "자체 AI 모듈이 있어 외부 AI 가입 없이 요약 같은 작업이 가능",
      "실행 후 모듈마다 처리 결과를 눌러서 확인할 수 있음",
      "무료 플랜이 기간 제한 없이 유지됨",
    ],
    cons: [
      "Maia가 만든 초안이 완성본이 아님 (시트 기록 단계 누락, AI 지시문 칸 비어 있음)",
      "값을 연결할 때 항목이 많아 어떤 것을 골라야 할지 알기 어려움",
      "다시 실행하면 이미 읽은 행은 건너뛰어, 시작 위치를 매번 재설정해야 함",
      "화면과 안내가 영어 중심",
      "무료는 활성 시나리오 2개, 실행 간격 최소 15분",
    ],
    price: [
      "무료: 월 1,000 크레딧, 활성 시나리오 2개, 최소 실행 간격 15분 (기간 제한 없음)",
      "Core: 월 $9부터 (연간 결제 기준, 1만 크레딧)",
      "상위: Pro, Teams, Enterprise",
    ],
    creditTips: [
      "모듈 실행 1회당 1 크레딧이므로, 단계(모듈) 수를 줄일수록 더 많이 실행 가능",
      "테스트 실행도 크레딧이 들어가니 소량 데이터로 먼저 확인하기",
      "실행 간격을 너무 짧게 두지 않기 (15분마다 돌면 하루 96회 실행)",
    ],
  },
  {
    name: "Dify",
    category: "automation",
    desc: "AI 챗봇, 에이전트, AI 작업 흐름을 코딩 없이 만드는 오픈소스 플랫폼",
    url: "https://dify.ai",
    freeLevel: "taste",
    freeAmount: "처음 1회 200 메시지 크레딧 → GPT-3.5급 약 200회 / GPT-4급 약 20회 (조사)",
    useCase: "고객 문의 응대 챗봇, 문서 요약과 분류처럼 AI가 중심인 업무",
    purposes: ["build"],
    pros: [
      "AI 챗봇, 에이전트, AI 작업 흐름을 코딩 없이 제작",
      "사내 문서를 올려 그 내용으로 답하는 챗봇을 만들 수 있음",
      "가입 직후 기본 크레딧으로 AI 모델 사용 가능",
      "오픈소스라 직접 설치하면 무료",
    ],
    cons: [
      "무료 크레딧이 200으로 적고, 매달 충전되지 않음 (조사)",
      "유료 플랜이 $59/월부터로 비쌈",
      "다른 앱과의 연결은 Make, n8n보다 약한 편",
      "조사 기반 정보 (직접 사용 전)",
    ],
    price: [
      "무료(Sandbox): 메시지 크레딧 200, 멤버 1명, 앱 5개",
      "Professional: $59/월 (월 5,000 크레딧)",
      "Team: $159/월 (월 1만 크레딧)",
      "직접 설치(셀프호스팅): 무료",
    ],
    creditTips: [
      "테스트할 때는 가벼운 모델을 선택하기 (상위 모델은 1회에 크레딧이 훨씬 많이 듦)",
      "자신의 AI API 키를 연결하면 기본 크레딧을 아낄 수 있음",
    ],
  },
  {
    name: "n8n",
    category: "automation",
    desc: "자유도가 높은 워크플로 자동화 도구로, 직접 설치하면 무료",
    url: "https://n8n.io",
    freeLevel: "paid",
    freeAmount: "클라우드는 14일 체험만 · 직접 설치하면 무료·무제한 (서버 필요)",
    useCase: "개발 인력이 있고, 자동화 실행량이 많거나 데이터를 사내에 두어야 하는 경우",
    purposes: [],
    pros: [
      "직접 설치하면 무료이고 실행 횟수 제한이 없음",
      "단계 수가 아니라 실행 1회 단위로 계산해 복잡한 흐름에 유리",
      "코드를 섞어 쓸 수 있어 자유도가 가장 높음",
      "데이터를 자체 서버에 둘 수 있음",
    ],
    cons: [
      "클라우드는 영구 무료 플랜 없이 14일 체험만 제공",
      "직접 설치하려면 서버와 관리 지식이 필요",
      "자동화 도구 셋 중 배우기 가장 어려움",
      "조사 기반 정보 (직접 사용 전)",
    ],
    price: [
      "클라우드: 영구 무료 플랜 없음, 14일 무료 체험",
      "Starter: 월 €20부터 (연간 결제 기준, 실행 2,500회)",
      "직접 설치(Community Edition): 무료, 실행 횟수 무제한",
    ],
    creditTips: [
      "실행 1회 단위 과금이라, 여러 단계를 하나의 워크플로로 묶을수록 유리함",
    ],
  },

  // ---------------- 리서치·검색 ----------------
  {
    name: "Perplexity",
    category: "research",
    desc: "궁금한 것을 바로 묻고, 출처 링크와 함께 빠르게 답을 얻는 AI 검색",
    url: "https://www.perplexity.ai/",
    freeLevel: "enough",
    freeAmount: "일반 검색 무료 · 고급 검색은 횟수 제한",
    useCase: "뉴스 조사, 팩트 체크",
    purposes: ["research"],
    source: "웹 전체 (뉴스, 블로그, 공식 사이트)",
    pros: ["답마다 출처 링크가 붙어 바로 검증할 수 있음", "사실 확인을 위한 자료 검색에 특화됨"],
    cons: ["무료는 고급 검색 횟수 제한"],
    price: ["무료 + 유료"],
  },
  {
    name: "NotebookLM",
    category: "research",
    desc: "내가 모은 자료 안에서만 답해 주는 나만의 자료 비서",
    url: "https://notebooklm.google.com",
    freeLevel: "enough",
    freeAmount: "자료 업로드·질문·음성 요약 기본 기능 무료",
    useCase: "강의자료·논문 요약, 시험 공부",
    purposes: ["paper", "research"],
    source: "사용자가 올린 자료 (웹에서 찾은 자료 추가 가능)",
    pros: [
      "올린 자료 안에서만 답해서 엉뚱한 답이 적음",
      "어느 부분에서 나온 답인지 표시해 줘서 지어낼 가능성이 낮음",
      "음성 요약 기능",
    ],
    cons: ["웹 검색이 아니라 자료를 먼저 넣어야 함"],
    price: ["무료 + 유료"],
  },
  {
    name: "Liner",
    category: "research",
    desc: "웹과 논문을 함께 찾고, 논문의 어느 문단이 근거인지까지 보여 주는 학술 검색",
    url: "https://app.liner.com/ko",
    freeLevel: "taste",
    freeAmount: "무료 플랜 있음 · 무료 기능 범위가 좁은 편",
    useCase: "레포트 참고문헌 찾기",
    purposes: ["paper"],
    korean: "good",
    source: "웹 + 학술 논문 (Scholar 모드)",
    pros: [
      "한국어 화면, 학술 자료 중심",
      "문단 단위로 출처를 달아줘서 자료 찾기가 쉬움",
      "초안 작성도 사이트 안에서 가능",
    ],
    cons: ["무료 기능 범위가 좁은 편"],
    price: ["무료 + 유료"],
  },
  {
    name: "Gemini Deep Research",
    category: "research",
    desc: "주제 하나로 웹을 넓게 조사해 보고서로 정리해 주는 AI",
    url: "https://gemini.google.com/",
    freeLevel: "taste",
    freeAmount: "무료 계정도 사용 가능 · 사용 횟수 제한 (공식 사이트 확인)",
    useCase: "과제 초반 자료 조사",
    purposes: ["research"],
    source: "웹 전체를 넓고 깊게 (허용하면 내 Gmail·Drive까지)",
    pros: [
      "조사 계획을 확인·수정한 뒤 보고서 작성 시작",
      "수많은 웹페이지를 읽고 보고서로 정리",
      "Google Docs로 바로 내보낼 수 있음",
    ],
    cons: ["시간이 몇 분 걸림", "분량이 길어 다시 읽고 정리해야 함"],
    price: ["무료 + 유료"],
    creditTips: ["횟수가 제한되므로 조사 계획 단계에서 범위를 충분히 다듬은 뒤 시작하기"],
  },
  {
    name: "Consensus",
    category: "research",
    desc: "연구 논문들이 어떤 주장에 얼마나 동의하는지 한눈에 보여 주는 AI",
    url: "https://consensus.app",
    freeLevel: "taste",
    freeAmount: "무료 플랜 있음 · 고급 분석은 횟수 제한 (공식 사이트 확인)",
    useCase: "어떤 주장이 과학적으로 맞는지 빠르게 확인",
    purposes: ["paper"],
    korean: "weak",
    source: "학술 논문만",
    pros: [
      "연구로 검증된 근거만 사용",
      "예/아니오 질문에 '연구 몇 %가 그렇다'처럼 합의 정도를 보여 줌",
    ],
    cons: [
      "예/아니오 질문에서만 합의 정도를 보여 주고, 열린 질문에는 장점이 줄어듦",
      "영어 논문 중심",
    ],
    price: ["무료 + 유료"],
    creditTips: ["'~은 효과가 있는가?'처럼 예/아니오 질문으로 바꿔 물어야 기능을 제대로 활용 가능"],
  },
  {
    name: "Elicit",
    category: "research",
    desc: "여러 논문의 연구 방법과 결과를 표로 뽑아 비교해 주는 AI",
    url: "https://elicit.com",
    freeLevel: "taste",
    freeAmount: "무료 플랜 있음 · 표 추출 등은 사용량 제한 (공식 사이트 확인)",
    useCase: "레포트나 논문 쓸 때 선행연구 비교·정리",
    purposes: ["paper"],
    source: "학술 논문만",
    pros: ["여러 논문에서 연구 방법, 대상 수, 결과 같은 항목을 뽑아 표로 정리"],
    cons: ["비교할 항목을 사용자가 정해야 해서 연구 주제를 어느 정도 알아야 잘 쓸 수 있음"],
    price: ["무료 + 유료"],
    creditTips: ["비교할 항목(연구 방법, 대상 수, 결과 등)을 미리 정해 두고 한 번에 추출하기"],
  },

  // ---------------- 웹·UI/UX 디자인 ----------------
  {
    name: "Google Stitch",
    category: "design",
    desc: "말로 설명하면 화면 시안을 여러 개 뽑아 비교하게 해 주는 무료 AI",
    url: "https://stitch.withgoogle.com",
    freeLevel: "enough",
    freeAmount: "무료로 사용 가능",
    useCase: "디자인 방향을 정하기 전 아이디어 얻기",
    purposes: ["build"],
    pros: ["무료이고, 시안을 여러 개 받아 비교할 수 있음", "Figma로 내보내기 가능"],
    cons: ["실험 단계라 기능이 자주 바뀜", "세밀한 수정은 어려움"],
    price: ["무료"],
  },
  {
    name: "클로드 디자인",
    category: "design",
    desc: "대화하면서 프로토타입과 발표 슬라이드를 만드는 AI",
    url: "https://claude.ai/design",
    freeLevel: "paid",
    freeAmount: "유료 요금제 필요 (무료 사용 범위 확인 필요)",
    useCase: "아이디어를 클릭되는 시제품으로 보여 줄 때",
    purposes: ["build", "slides"],
    pros: [
      "대화로 수정하며 프로토타입과 슬라이드를 함께 만들 수 있음",
      "글씨 크기와 위치 같은 요소 값을 직접 조절할 수 있어 원하는 모양을 바로 만들 수 있음",
      "반복 지시가 줄어 토큰 절약에도 도움",
    ],
    cons: ["2026년 4월에 나온 서비스라 참고 자료가 적음", "무료 사용 범위 확인 필요"],
    price: ["유료"],
  },
  {
    name: "v0",
    category: "design",
    desc: "말로 설명한 화면을 실제로 작동하는 코드로 만들어 주는 AI",
    url: "https://v0.dev",
    freeLevel: "taste",
    freeAmount: "무료 크레딧 범위 안에서 사용 (공식 사이트 확인)",
    useCase: "디자인을 실제 웹페이지로 옮길 때",
    purposes: ["build"],
    pros: ["미리보기 화면과 코드가 함께 나와 바로 개발에 쓸 수 있음"],
    cons: ["React 기반 코드가 기본이라 HTML 과제에는 따로 요청해야 함"],
    price: ["무료 + 유료"],
    creditTips: ["처음 요청에 'HTML·CSS·JavaScript로'를 명시해 다시 만드는 횟수 줄이기"],
  },
  {
    name: "Figma",
    category: "design",
    desc: "AI로 만든 화면을 세밀하게 직접 다듬는 업계 표준 디자인 툴",
    url: "https://www.figma.com",
    freeLevel: "enough",
    freeAmount: "개인 무료 플랜으로 기본 디자인 작업 가능",
    useCase: "시안을 완성도 있게 다듬을 때",
    purposes: ["build"],
    pros: [
      "원하는 대로 세밀하게 수정 가능",
      "팀원과 동시 작업",
      "요소 하나하나를 조정할 수 있어 화면 완성도를 높이기에 적합",
    ],
    cons: ["기능이 많아 처음에 익히는 데 시간이 걸림"],
    price: ["무료 + 유료"],
  },
  {
    name: "Canva",
    category: "design",
    desc: "템플릿과 AI로 배너·포스터 같은 그래픽을 빠르게 만드는 툴",
    url: "https://www.canva.com/ko_kr/",
    freeLevel: "enough",
    freeAmount: "기본 템플릿·편집 무료 · AI 기능은 월 소량 크레딧",
    useCase: "홍보물, 썸네일, 카드뉴스",
    purposes: ["promo"],
    korean: "good",
    pros: ["템플릿이 많아 디자인 경험이 없어도 쉬움", "PPT와 비슷해서 초보자도 쉽게 접근 가능"],
    cons: ["웹 화면 설계보다는 그래픽에 강함"],
    price: ["무료 + 유료 (Pro 월 ₩9,900)"],
  },
  {
    name: "Framer",
    category: "design",
    desc: "프롬프트로 웹사이트를 만들고 바로 인터넷에 배포하는 툴",
    url: "https://www.framer.com",
    freeLevel: "enough",
    freeAmount: "무료로 사이트 제작·공개 가능 · 도메인과 페이지 수 제한",
    useCase: "포트폴리오·소개 사이트를 빨리 공개할 때",
    purposes: ["build"],
    pros: ["코딩 없이 사이트를 만들고 바로 공개"],
    cons: ["무료 플랜은 도메인과 페이지 수에 제한"],
    price: ["무료 + 유료"],
  },

  // ---------------- 이미지 생성·편집 ----------------
  {
    name: "Ideogram",
    category: "image",
    desc: "글자 타이포그래피 구현에 특화된 이미지 생성 AI",
    url: "https://ideogram.ai/",
    freeLevel: "enough",
    freeAmount: "매일 10회 느린 생성 → 1회 4장씩, 시안 약 40장",
    useCase: "영문 타이포그래피 로고 시안, 영문 포스터 및 굿즈 그래픽",
    purposes: ["promo"],
    korean: "weak",
    pros: [
      "기본 생성 시 4가지 시안을 한 번에 제공해 의도에 가까운 결과를 고르기 쉬움",
      "커뮤니티 피드에서 고품질 결과물의 프롬프트를 보고 배울 수 있음",
    ],
    cons: ["한국어 텍스트 이해도는 떨어지는 편", "무료 플랜은 JPEG만 다운로드 가능"],
    price: [
      "무료: 매일 10회 느린 생성 크레딧 리셋",
      "Basic: 월 $8 / Plus: 월 $20부터",
    ],
    creditTips: [
      "커뮤니티 피드에서 비슷한 결과물의 프롬프트를 먼저 참고하면 생성 횟수를 아낄 수 있음",
      "넣을 글자는 영어로, 따옴표로 묶어서 지정하기",
    ],
  },
  {
    name: "Canva (Magic Studio)",
    category: "image",
    desc: "생성부터 배경 제거(누끼)까지 처리하는 실무 디자인 툴",
    url: "https://www.canva.com/ko_kr/",
    freeLevel: "taste",
    freeAmount: "기본 기능 + 월별 소량 AI 크레딧 · 핵심 AI 편집은 Pro",
    useCase: "SNS 콘텐츠/배너 제작, 발표용 템플릿, 카드뉴스 및 마케팅 디자인",
    purposes: ["promo"],
    korean: "good",
    pros: [
      "이미지 편집, 시각화 편집에 강점",
      "이미지 일러스트 레이어 나누기, 배경 제거(누끼) 기능이 뛰어남",
      "웹 기반이라 직관적이고, 기능이 다양해도 UI가 다루기 편함",
    ],
    cons: ["핵심 AI/편집 기능은 Canva Pro 구독 필수"],
    price: [
      "무료: 기본 기능 및 월별 소량 AI 크레딧",
      "Pro: 월 9,900원 (연간 99,000원)",
    ],
    creditTips: ["AI 생성은 소량 크레딧이므로, 무료 템플릿으로 틀을 먼저 잡고 꼭 필요한 부분만 AI로 생성하기"],
  },
  {
    name: "Midjourney",
    category: "image",
    desc: "극사실주의 묘사와 예술적 질감 표현에 특화된 대표 이미지 생성 AI",
    url: "https://www.midjourney.com/",
    freeLevel: "paid",
    freeAmount: "무료 체험 불가 · Basic 월 $10부터",
    useCase: "포토리얼 인물/배경, 판타지·SF 컨셉 아트, 고화질 상업용 일러스트 시안",
    purposes: ["promo"],
    pros: ["압도적인 사실적 그래픽 디테일", "조명·질감 묘사 최상급", "예술적 연출력 탁월"],
    cons: [
      "무료 체험이 없어 최소 결제 필수",
      "복잡한 영문 타이포그래피(글자 철자)는 Ideogram보다 아쉬움",
    ],
    price: ["유료 전용 (무료 체험 불가)", "Basic 플랜: 월 $10부터"],
  },

  // ---------------- 회의록·기록 ----------------
  {
    name: "클로바노트",
    category: "meeting",
    desc: "네이버 하이퍼클로바 기반으로 한국어 구어체까지 정확히 받아적는 서비스",
    url: "https://clovanote.naver.com/",
    freeLevel: "enough",
    freeAmount: "매월 300분 무료 (데이터 수집 동의 시 최대 600분)",
    useCase: "오프라인 미팅 녹음 및 전사, 인터뷰 정리, 회의 시간대별 핵심 요약",
    purposes: ["meeting"],
    korean: "good",
    pros: [
      "한국어 구어체/방언 인식률 최상급",
      "화자 분리 우수",
      "네이버 계정 연동 및 모바일-PC 동기화 편리",
      "인터페이스가 깔끔해 처음 써도 진입장벽이 낮음",
    ],
    cons: [
      "글로벌 언어 지원 종류가 상대적으로 적음",
      "녹취록을 바탕으로 대화형 질문을 던지는 기능이 부족함",
    ],
    price: ["매월 300분 무료 (데이터 수집 동의 시 최대 600분)"],
    creditTips: ["데이터 수집에 동의하면 무료 시간이 최대 600분까지 늘어남 (회의 내용 보안은 확인 후 결정)"],
  },
  {
    name: "다글로",
    category: "meeting",
    desc: "회의 녹음, 유튜브 링크, 오디오 파일을 텍스트로 바꾸고 분석하는 기록 AI",
    url: "https://daglo.ai/",
    freeLevel: "enough",
    freeAmount: "매월 1,000 크레딧 → 약 4시간 전사",
    useCase: "강의·사내 교육 복습, 인터뷰 정리, 회의 내용으로 발표자료(PPT/퀴즈) 초안 제작",
    purposes: ["meeting", "slides"],
    korean: "good",
    pros: [
      "녹음 내용을 바탕으로 PPT 슬라이드 및 퀴즈 제작 기능",
      "받아쓴 텍스트로 대화형 질의응답(보드챗) 가능",
      "노션 연결",
    ],
    cons: [
      "대용량·장시간 오디오 파일 전사 시 처리 지연이 생길 수 있음",
      "전문 용어 인식 오차 가능",
    ],
    price: ["무료: 매월 1,000 크레딧 (약 4시간 상당)", "Pro: 월 11,900원부터"],
    creditTips: ["녹음 앞뒤의 불필요한 구간을 잘라내고 올리면 크레딧을 아낄 수 있음"],
  },
  {
    name: "Otter.ai",
    category: "meeting",
    desc: "실시간 회의에 봇이 참여해 영문 전사 및 회의록을 생성하는 글로벌 툴",
    url: "https://otter.ai/",
    freeLevel: "enough",
    freeAmount: "매월 300분 (1회 미팅당 최대 30분) · 영어 회의 기준",
    useCase: "글로벌 영어 화상 미팅 실시간 전사, 해외 바이어 미팅 및 웨비나 기록",
    purposes: ["meeting"],
    korean: "weak",
    pros: [
      "Zoom, Teams, Meet 캘린더 자동 연동",
      "실시간 화면 캡처 및 영문 회의록 템플릿 요약 우수",
      "영문 미팅 시 봇이 알아서 회의록과 캡처본을 남겨줌",
    ],
    cons: ["한국어 음성 인식률 및 지원 완성도가 낮음", "무료 플랜은 1회 미팅당 30분 제한"],
    price: [
      "Basic 무료: 매월 300분 (1회 미팅당 최대 30분)",
      "Pro: 연간 결제 시 월 $8.33 / 월간 결제 시 $16.99",
    ],
  },

  // ---------------- 시각화·PPT ----------------
  {
    name: "Canva",
    category: "ppt",
    desc: "템플릿 기반 올인원 디자인 툴",
    url: "https://www.canva.com/ko_kr/",
    freeLevel: "enough",
    freeAmount: "기본 템플릿으로 발표 자료 제작 무료 · 고급 템플릿·아이콘은 유료",
    useCase: "카드뉴스, 간단한 발표 자료",
    purposes: ["slides", "promo"],
    korean: "good",
    pros: ["방대한 템플릿", "세부 조정 및 협업 용이", "초보도 금방 안정적인 퀄리티의 결과물을 낼 수 있음"],
    cons: ["퀄리티 높은 템플릿과 아이콘 요소 대부분이 유료"],
    price: ["무료 + 유료 (Pro 월간 ₩9,900)"],
  },
  {
    name: "Gamma",
    category: "ppt",
    desc: "프롬프트로 PPT를 만들어 주는 AI",
    url: "https://gamma.app/",
    freeLevel: "taste",
    freeAmount: "무료 크레딧 범위 안에서 초안 제작 (공식 사이트 확인)",
    useCase: "발표 초안, 빠른 공유용 자료",
    purposes: ["slides"],
    pros: ["몇 분 만에 초안 완성 가능", "PPT의 대략적인 틀을 잡을 때 매우 유용함"],
    cons: ["세부 수정 자유도가 비교적 낮음"],
    price: ["무료 + 유료 (Plus 월간 $12)"],
    creditTips: ["목차와 핵심 내용을 미리 정리해서 한 번에 넣으면 다시 생성하는 횟수가 줄어듦"],
  },

  // ---------------- 음성·번역 ----------------
  {
    name: "DeepL",
    category: "voice",
    desc: "문맥을 살린 자연스러운 문장의 AI 번역기",
    url: "https://www.deepl.com/ko/translator",
    freeLevel: "enough",
    freeAmount: "텍스트 번역 무료 · 문서 파일 번역은 횟수 제한",
    useCase: "업무 메일, 보고서, 논문",
    purposes: ["translate", "paper"],
    pros: [
      "문맥을 살린 번역",
      "문서 파일 번역 특화, 여러 파일 일괄 번역 가능",
      "많은 양의 외국어를 한 번에 빠르게 읽거나 번역할 때 좋음",
    ],
    cons: ["무료 버전은 문서 번역 횟수 제한"],
    price: ["무료 + 유료 (Individual 월 $10.49)"],
    creditTips: ["문서 번역 횟수가 제한되므로, 짧은 글은 텍스트 창에 붙여 넣어 번역하기"],
  },
  {
    name: "Papago",
    category: "voice",
    desc: "한국어에 특화된 네이버 번역기",
    url: "https://papago.naver.com/",
    freeLevel: "enough",
    freeAmount: "일상적인 번역은 무료로 충분",
    useCase: "단어 검색, 일상 대화, 여행",
    purposes: ["translate"],
    korean: "good",
    pros: ["자연스러운 구어체", "접근성 편리", "요금 제약이 낮아 가볍게 쓰기에 가장 편함"],
    cons: ["긴 전문 문서에는 약함"],
    price: ["무료 + 유료 (Plus Basic 월 ₩13,000)"],
  },
  {
    name: "ElevenLabs",
    category: "voice",
    desc: "사람 같은 목소리를 만드는 AI 음성 툴",
    url: "https://elevenlabs.io",
    freeLevel: "taste",
    freeAmount: "무료 플랜 있음 · 월 사용량 제한 (공식 사이트 확인)",
    useCase: "영상 내레이션, 더빙",
    purposes: ["translate", "makevideo"],
    korean: "normal",
    pros: [
      "자연스러운 감정 표현",
      "음성 세부 조정 용이",
      "목소리 복제 가능",
      "다른 음성 툴보다 덜 기계적임",
    ],
    cons: ["가끔 한국어 억양이 어색함"],
    price: ["무료 + 유료 (Creator $11)"],
    creditTips: ["글자 수 단위로 사용량이 줄어드니, 짧은 문장으로 목소리·톤을 먼저 테스트한 뒤 전체 원고 생성하기"],
  },

  // ---------------- 범용 AI 에이전트 ----------------
  {
    name: "Manus",
    category: "agent",
    desc: "자료 조사를 다양한 곳에서 하고, PPT의 대략적인 흐름을 잡아 주는 AI 에이전트",
    url: "https://manus.im",
    freeLevel: "taste",
    freeAmount: "매일 300 크레딧 → 작업 약 2개",
    useCase: "다양한 곳에서 자료 조사하기를 원할 때",
    purposes: ["research", "slides"],
    pros: ["출처를 제대로 표기", "다양한 곳에서 데이터 수집"],
    cons: [
      "데이터를 끌어오는 작업이 상당히 오래 걸림",
      "출처가 불명확하거나 신뢰도가 떨어지는 데이터를 수집할 때가 있음",
      "PPT는 내용이 빈약하고 디자인이 아쉬움",
      "결과가 정리가 잘 안 되어 있어 참고 자료로만 쓰는 것이 좋음",
    ],
    price: [
      "무료: 매일 300 크레딧 (작업 2개 정도 요청하면 소진)",
      "Pro 월 4,000 크레딧: 3개월간 월 $10, 이후 월 $20",
      "Pro 월 8,000 크레딧: 3개월간 월 $30, 이후 월 $40",
      "Pro 월 40,000 크레딧: 3개월간 월 $190, 이후 월 $200",
    ],
    creditTips: [
      "요청을 여러 번 나누지 말고, 범위·출처 조건·결과 형식을 한 번에 구체적으로 적기",
      "결과의 수치는 출처별 정의와 연도가 다를 수 있으니 원문을 꼭 확인하기",
    ],
  },
  {
    name: "Genspark",
    category: "agent",
    desc: "대시보드를 단계별로 간단하게 만들어 보는 AI 에이전트",
    url: "https://www.genspark.ai/",
    freeLevel: "taste",
    freeAmount: "매일 100 크레딧 · 공개되지 않은 총 사용 한도 있음 (조사)",
    useCase: "대시보드 제작 과정을 단계별로 확인하며 빠르게 시각화 초안을 만들고 싶을 때",
    purposes: ["build", "slides"],
    korean: "normal",
    pros: [
      "용도에 맞는 대시보드 템플릿을 다양하게 제공",
      "만들어지는 과정을 단계별로 세세하게 보여줌",
      "대시보드를 단계에 맞게 체계적으로 완성",
    ],
    cons: [
      "시스템 일부가 영어로 표기됨",
      "시간이 좀 오래 걸림",
      "템플릿 디자인이 아쉬움",
      "필요한 정보를 한 번에 묻지 않고 단계별로 하나씩 요청함",
    ],
    price: [
      "무료: 매일 100 크레딧",
      "1단계 (월 10,000 크레딧): 월 $24.99",
      "2단계 (월 21,000 크레딧): 월 $49.99",
      "3단계 (월 125,000 크레딧): 월 $249.99",
    ],
    creditTips: ["단계별로 정보를 물어보니, 필요한 데이터·항목을 미리 준비해 두고 바로 답하기"],
  },

  // ---------------- 바이브 코딩 ----------------
  {
    name: "Cursor",
    category: "coding",
    desc: "AI가 코드 작성과 수정을 도와주는 코딩 프로그램",
    url: "https://cursor.com",
    freeLevel: "taste",
    freeAmount: "무료 Hobby 플랜 · 에이전트 요청 제한 (정확한 횟수 비공개) + Pro 1주 체험 (조사)",
    useCase: "간단한 코딩 결과를 빠르게 보고 싶을 때",
    purposes: ["build"],
    pros: [
      "사용자 작업에 맞는 프롬프트/수정 방향 제안",
      "웹 기반 AI 툴보다 코드 반영 및 실행 속도가 빠름",
    ],
    cons: [
      "따로 다운로드해야 하고, 설치·실행까지 시간이 걸림",
      "사용법이 약간 복잡함",
      "실행은 빠르지만 결과 퀄리티는 아쉬웠음",
    ],
    price: [
      "무료: Hobby 플랜 (요청 수 제한, 조사)",
      "Pro: 월 $20 / Pro+: 월 $60 / Ultra: 월 $200",
    ],
    creditTips: ["무료 요청이 제한되므로, 수정할 파일과 원하는 결과를 한 번에 구체적으로 지시하기"],
  },
  {
    name: "Windsurf",
    category: "coding",
    desc: "AI가 알아서 파일과 터미널을 오가며 코딩해 주는 프로그램",
    url: "https://windsurf.com",
    freeLevel: "taste",
    freeAmount: "자동완성 무제한 · 에이전트 작업 월 약 25회 (조사)",
    useCase: "다중 파일(풀스택) 웹/앱 개발, 터미널 작업 자동화",
    purposes: ["build"],
    pros: [
      "여러 파일을 스스로 탐색하고 터미널 명령어까지 알아서 실행",
      "Cursor보다 전체 코드 맥락 파악 및 연계 수정 능력이 뛰어남",
      "파일을 하나하나 지정하지 않아도 필요한 코드를 찾아 수정해 줌",
    ],
    cons: [
      "프로그램을 따로 설치해야 함",
      "프로젝트 규모가 커지면 인덱싱 시간이 걸림",
      "가끔 의도하지 않은 다른 파일을 건드리거나 에러 루프에 빠짐 → 중간 확인 필요",
    ],
    price: [
      "무료: 월 약 25회 에이전트 작업 (조사)",
      "Pro: 월 $20 / Teams: 월 $80 / Max: 월 $200",
    ],
    creditTips: ["에이전트 작업 횟수가 적으므로 간단한 수정은 자동완성으로 처리하고, 큰 작업만 에이전트에 맡기기"],
  },
];
